export const SET_CURRENT_AD = `SET_CURRENT_AD`;
export const DISMISS_AD = `DISMISS_AD`

export const AD_LIST_REQUEST = 'AD_LIST_REQUEST'
export const AD_LIST_SUCCESS = 'AD_LIST_SUCCESS'
export const AD_LIST_FAIL = 'AD_LIST_FAIL'
export const AD_LIST_RESET = 'AD_LIST_RESET'

export const AD_CREATE_REQUEST = 'AD_CREATE_REQUEST'
export const AD_CREATE_SUCCESS = 'AD_CREATE_SUCCESS'
export const AD_CREATE_FAIL = 'AD_CREATE_FAIL'
export const AD_CREATE_RESET = 'AD_CREATE_RESET'

export const AD_DELETE_REQUEST = 'AD_DELETE_REQUEST'
export const AD_DELETE_SUCCESS = 'AD_DELETE_SUCCESS'
export const AD_DELETE_FAIL = 'AD_DELETE_FAIL'
export const AD_DELETE_CLEAR_MESSAGE = 'AD_DELETE_CLEAR_MESSAGE'
export const AD_DELETE_HIDE_MESSAGE = 'AD_DELETE_HIDE_MESSAGE'

export const AD_UPDATE_REQUEST = 'AD_UPDATE_REQUEST'
export const AD_UPDATE_SUCCESS = 'AD_UPDATE_SUCCESS'
export const AD_UPDATE_FAIL = 'AD_UPDATE_FAIL'
export const AD_UPDATE_RESET = 'AD_UPDATE_RESET'
export const AD_UPDATE_HIDE_MESSAGE = 'AD_UPDATE_HIDE_MESSAGE'

export const AD_DETAILS_REQUEST = 'AD_DETAILS_REQUEST'
export const AD_DETAILS_SUCCESS = 'AD_DETAILS_SUCCESS'
export const AD_DETAILS_FAIL = 'AD_DETAILS_FAIL'
